PUBLIC DISPLAY_NUMBER_CONTENT
EXTRN CODE (DISPLAY_NUM_TUBE)
DISPLAY_NUMBER_CONTENT:
;队伍分数和计时初始化
SETB RS0 ;设置当前工作寄存器区为1区
MOV R0,#32H
MOV R1,#7
INI_DISPLAY:
MOV @R0,#00H
INC R0
DJNZ R1,INI_DISPLAY
;输入的计时秒数段码显示
MOV A,00H
CLR C
SUBB A,#03H
;1区R0用于记录当前查表位
;1区R1用于存放指针
MOV R2,#33H ;1区R2用于记录数码管尾址
MOV R3,#03H ;1区R3用于记录当前数的地址
MOV R4,A ;1区R4用于记录当前有多少个数
XCH A,R2
ADD A,R2
XCH A,R2
JZ DISP_END
CALC_AND_PUT:
MOV A,#80H
MOV R1,0BH ;将当前数的地址放入R1
ADD A,@R1 ;计算查哪个位
MOV R0,A
MOV A,@R0 ;查表
MOV R1,0AH
MOV @R1,A ;存放段码
DEC R2
INC R3
DJNZ R4,CALC_AND_PUT ;循环放计时值
DISP_END:
JB 03H,HEX_TRANSLATE ;选择进制
TRANSFER_DIGIT:
;A队分数译码
MOV A,31H
MOV B,#10
DIV AB
ADD A,#80H ;分数的十位
MOV R0,A
MOV A,@R0 ;查表
MOV 39H,A ;放入十位的段码
MOV A,B
ADD A,#80H ;分数的个位
MOV R0,A
MOV A,@R0 ;查表
MOV 38H,A ;放入个位的段码
;B队分数译码
MOV A,30H
MOV B,#10
DIV AB
ADD A,#80H ;分数的十位
MOV R0,A
MOV A,@R0 ;查表
MOV 33H,A ;放入十位的段码
MOV A,B
ADD A,#80H
MOV R0,A
MOV A,@R0
MOV 32H,A ;放入个位的段码
AJMP CALL_DISPLAY_FUNC
HEX_TRANSLATE:
;A队分数译码
MOV A,31H
MOV B,#16
DIV AB
ADD A,#80H ;分数的十位
MOV R0,A
MOV A,@R0 ;查表
MOV 39H,A ;放入十位的段码
MOV A,B
ADD A,#80H ;分数的个位
MOV R0,A
MOV A,@R0 ;查表
MOV 38H,A ;放入个位的段码
;B队分数译码
MOV A,30H
MOV B,#16
DIV AB
ADD A,#80H ;分数的十位
MOV R0,A
MOV A,@R0 ;查表
MOV 33H,A ;放入十位的段码
MOV A,B
ADD A,#80H
MOV R0,A
MOV A,@R0
MOV 32H,A ;放入个位的段码
CALL_DISPLAY_FUNC:
CLR RS0 ;换回0区
LCALL DISPLAY_NUM_TUBE
RET
END