EXTRN CODE (INITIALIZATION_PROG)
EXTRN CODE (ENTER_TIME)
EXTRN CODE (LOAD_IN_TIMER)
EXTRN CODE (START_RACE)
EXTRN CODE (TEAM_A_SCORE)
EXTRN CODE (T0INT)
EXTRN CODE (TEAM_B_SCORE)
EXTRN CODE (T1INT)
EXTRN CODE (BEEP)
EXTRN CODE (END_RACE)
EXTRN CODE (T2INT)
ORG 0000H
AJMP MAIN
ORG 0003H
LJMP INT0INT ;A队得分中断
ORG 000BH
LCALL T0INT ;T0中断
ORG 0013H
LJMP INT1INT ;B队得分中断
ORG 001BH
LJMP T1INT ;T1中断
ORG 002BH 
LJMP T2INT ;T2中断
ORG 0030H
MAIN:
MOV SP,#60H ;堆栈上移
LCALL INITIALIZATION_PROG ;初始化
LCALL ENTER_TIME ;输入定时时长,准确秒数高8位放在R1，低8位放在R2，R0-3是多少位的计时秒数
LCALL START_RACE;开始比赛
LCALL END_RACE;比赛结束，蜂鸣和显示结果
AJMP MAIN
END