PUBLIC DISPLAY_MATRIX_LED
EXTRN CODE (DELAY_FOR_DIGIT_SHOW)
DISPLAY_MATRIX_LED:
SETB RS0 ;换到1区工作寄存器
JB 04H,SECOND_CONDITION
MOV R0,#41H
AJMP MATRIX_DISP_FUNC
SECOND_CONDITION:
MOV R0,#49H
MATRIX_DISP_FUNC:
CLR SRCLK
CLR RCLK ;清空点阵时钟
MOV R5,#08H
MOV 56H,#7FH
MATRIX_DISP_LOOP:
MOV 51H,@R0
LCALL MATRIX_SENDBYTE
INC R0
MOV A,56H
MOV P0,A ;发送位码
RR A
MOV 56H,A
SETB RCLK ;给一个上升沿使595输出数据
NOP
NOP
CLR RCLK
LCALL DELAY_FOR_DIGIT_SHOW ;短延时
MOV 51H,#00H ;消除余辉
LCALL MATRIX_SENDBYTE
SETB RCLK ;给一个上升沿使595输出00H
NOP
NOP
CLR RCLK
LCALL DELAY_FOR_DIGIT_SHOW
DJNZ R5,MATRIX_DISP_LOOP
CLR RS0 ;换回0区
RET
END