PUBLIC START_RACE
EXTRN CODE (DISPLAY_NUMBER_CONTENT)
EXTRN CODE (DELAY_KEYBOARD)
EXTRN CODE (TEAM_A_SCORE)
EXTRN CODE (TEAM_B_SCORE)
START_RACE:
SETB EA
SETB ET0
LCALL DISPLAY_NUMBER_CONTENT
;检测是否转换进制 P3.0
SETB P3.0
JB P3.0,CHECK_WHETHER_START
LCALL DELAY_KEYBOARD ;消抖
SETB P3.0
JB P3.0,CHECK_WHETHER_START
CPL 03H ;转换进制
CPL TR0 ;转换T0开关状态
TRANSFER_NOT_RELEASE:
LCALL DISPLAY_NUMBER_CONTENT
SETB P3.0
JNB P3.0,TRANSFER_NOT_RELEASE
LCALL DELAY_KEYBOARD ;消抖
SETB P3.0
JNB P3.0,TRANSFER_NOT_RELEASE
CHECK_WHETHER_START:
;检测开始比赛按钮 P3.1
SETB P3.1
JB P3.1,START_RACE ;比赛开始按钮没有按下
LCALL DELAY_KEYBOARD ;消抖
SETB P3.1
JB P3.1,START_RACE
;开始比赛按键按下，开定时器1、2中断，不允许加减分（不开外部中断）
SETB ET2
SETB ET1
SETB P1.0 ;准备计数脉冲
SETB P3.2 ;准备计分中断
SETB P3.3
CLR TR0 ;关闭进制蜂鸣
CHECK_START_BUTTON_UP: ;检查开始按钮是否松开
LCALL DISPLAY_NUMBER_CONTENT
SETB P3.1
JNB P3.1,CHECK_START_BUTTON_UP
LCALL DELAY_KEYBOARD ;消抖
SETB P3.1
JNB P3.1,CHECK_START_BUTTON_UP
;开始按钮松开，比赛开始
SETB 00H ;更新比赛开始标志位
SETB TR2 ;启动计数器计数
SETB TR1 ;启动定时器倒计时
SETB P3.0
SETB EX0 ;启动两队计分
SETB EX1
CLR 02H ;更新比赛暂停标志位
CLR 10H	;更新A队加分标志位
CLR 11H ;更新B队加分标志位
RET
SCAN_MATCH:
LCALL DISPLAY_NUMBER_CONTENT
JB P3.0,CHECK_A_TEAM ;检测暂停键是否按下
SETB P3.0
LCALL DELAY_KEYBOARD ;消抖
JB P3.0,CHECK_A_TEAM ;没有按下，继续
CPL 02H
JNB 02H,CANCEL_PAUSE
CLR TR2	;开始暂停
PAUSE_WAIT:
LCALL DISPLAY_NUMBER_CONTENT
SETB P3.0
JNB P3.0,PAUSE_WAIT
SETB P3.0
LCALL DELAY_KEYBOARD ;消抖
JNB P3.0,PAUSE_WAIT
AJMP CHECK_A_TEAM
CANCEL_PAUSE: ;取消暂停
LCALL DISPLAY_NUMBER_CONTENT
SETB P3.0
JNB P3.0,CANCEL_PAUSE
SETB P3.0
LCALL DELAY_KEYBOARD ;消抖
JNB P3.0,CANCEL_PAUSE
SETB TR2
CHECK_A_TEAM:
JNB 10H,CHECK_B_TEAM
LCALL TEAM_A_SCORE ;A队加分
CHECK_B_TEAM:
JNB 11H,CHECK_MATCH_END
LCALL TEAM_B_SCORE ;B队加分
CHECK_MATCH_END: ;检查比赛是否结束
JB 00H,SCAN_MATCH
RET
END