PUBLIC T0INT
PUBLIC T1INT
PUBLIC T0INT
EXTRN CODE (DISPLAY_NUMBER_CONTENT)
T2INT:
CLR TF2
PUSH 0E0H ;保护累加器内容
PUSH 0D0H ;保护状态字
JNB 00H,AFTER_RACE_TIMER
CLR RS1 ;换回0区
CJNE R0,#07H,TIME_THREE_DIGIT
;目前仍然是四位数
MOV A,R6 ;处理个位
JZ MINUS1 ;个位为0，需要借位
DEC R6
AJMP RETURNABLE
MINUS1:
MOV R6,#09H
MOV A,R5 ;处理十位
JZ MINUS2 ;十位为0，需要借位
DEC R5
AJMP RETURNABLE
MINUS2:
MOV R5,#09H
MOV A,R4 ;处理百位
JZ MINUS3 ;百位为0，需要借位
DEC R4
AJMP RETURNABLE
MINUS3:
MOV R4,#09H
DEC R3 ;处理千位
MOV A,R3
JNZ RETURNABLE
DEC R0 ;减完后只剩三位了，进行整体移动
MOV R3,R4
MOV R4,R5
MOV R5,R6
AJMP RETURNABLE
TIME_THREE_DIGIT:
CJNE R0,#06H,TIME_TWO_DIGIT
;目前是三位数
MOV A,R5 ;处理个位
JZ MINUS4 ;个位为0，需要借位
DEC R5
AJMP RETURNABLE
MINUS4:
MOV R5,#09H
MOV A,R4 ;处理十位
JZ MINUS5 ;十位为0，需要借位
DEC R4
AJMP RETURNABLE
MINUS5:
MOV R4,#09H
DEC R3 ;处理百位
MOV A,R3
JNZ RETURNABLE
DEC R0 ;减完后只剩两位了，进行整体移动
MOV R3,R4
MOV R4,R5
AJMP RETURNABLE
TIME_TWO_DIGIT:
CJNE R0,#05H,TIME_ONE_DIGIT
;目前是两位数
MOV A,R4 ;处理个位
JZ MINUS6 ;个位为0，需要借位
DEC R4
AJMP RETURNABLE
MINUS6:
MOV R4,#09H
DEC R3 ;处理十位
MOV A,R3 
JNZ RETURNABLE
DEC R0 ;减完后只剩一位了，进行整体移动
MOV R3,R4
AJMP RETURNABLE
TIME_ONE_DIGIT:
;目前是一位数
MOV A,R3 ;处理个位
JZ TIME_UP ;时间到（处理输入0的情况）
DEC R3
MOV A,R3
JZ TIME_UP ;减完后时间到
AJMP RETURNABLE
TIME_UP: ;时间到了
CLR TR1 ;关定时器
CLR 00H ;清比赛开始位
CLR 02H ;清比赛暂停位
DEC R0
AJMP RETURNABLE
AFTER_RACE_TIMER:
SETB RS0 ;换3区工作寄存器
SETB RS1
CPL 04H ;显示状态改变
JNB TR0,RETURNABLE ;T0不工作保留原音乐数据
MOV A,55H ;音乐步骤改变
CJNE A,#0DEH,NEXT_MUSIC
MOV 55H,#0CAH
AJMP READ_MUSIC
NEXT_MUSIC:
ADD A,#2
MOV 55H,A
READ_MUSIC:
MOV R0,55H
MOV R1,55H
INC R1
MOV 53H,@R0	;换音调
MOV 54H,@R1
RETURNABLE:
POP 40H ;还原累加器内容
MOV A,40H
MOV RS0,03H
MOV RS1,04H ;恢复选区
RETI
T1INT:
CLR P1.0
SETB P1.0 ;给T2一个外部脉冲，使其计数
RETI
T0INT:
CPL P1.5 ;蜂鸣器响
MOV TH0,53H
MOV TL0,54H
RETI ;用掉8个机器周期
END